version: '3'
services:
#  stream_server:
#    image: stream-nginx
#    ports:
#      - "80:8080"  # Change the port if needed
#      - "1935:1935"
#    volumes:
 #     - ./origin.conf:/etc/nginx/nginx.conf:ro
      
  edge:
    image: nginx:stable
    volumes:
      - ./edge.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - stream_server
    ports:
      - "8081:80"
